# Site
repository: Charrrrrlie/Charrrrrlie.github.io

favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yuchen Yang
title: Hard to definate
email: charles.yyc@foxmail.com
website: charrrrrlie.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Charrrrrlie
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  (updated on 2021.11.11)

  Hello there! My name's Yuchen Yang or you can call me Charles, Charrrrrlie (with a long drawl, as the unique site).

  I'm currently a Ph.D. candidate who will study further at Fudan University and Shanghai AI Lab in a co-supervised project.
  
  What I'm going to explore is Computer Vision, especially Perceptron in Autonomous Driving.
  
  Before that, I studied at Wuhan University and focused on (remote sensing) Image Compression and Restoration in the Lab. of Intelligent Information Processing, supervised by [Prof.ZhenZhong Chen](iip.whu.edu.cn)

  To know more about my non-academic interests, you can scroll down and read the list at the bottom.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wuhan University
        caption: September 2018 - June 2022
        sub_title: B.E. Remote Sensing
        quote: >
          Not only Sakura, but also my beloved friends and passed years.
        description: | # this will include new lines to allow paragraph
          During my time in university, most time is spent on studying or the way to study. Luckily, however, I seize the opportunity to try new things and learn something "useless" which strengthened my comprehension of campus life.
          Memories, to win a school-level basketball competition, to film a documentary gazing at body shame, or just to hang out with my best friends, are becoming a despairing part of me.  
 
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: <mark>CVPRW 2021</mark> Dual-Modality Vehicle Anomaly Detection via Bilateral Trajectory Tracing
        link: https://arxiv.org/abs/2106.05003
        # link_text: arXiv Website
        additional_links:
          - title:  CVPRW_AICity_2021
            icon: fab fa-github
            url: https://github.com/jingyuanchan/CVPR_AICity_2021_Anomaly_Detection
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Jingyuan Chen*, Guanchen Ding*, **Yuchen Yang** *, Wenwei Han, Kangmin Xu, Tianyi Gao, Zhe Zhang, Wanping Ouyang, Hao Cai, Zhenzhong Chen
          2021 CVPRW AICity Challenge. Work done in Lab. IIP in Wuhan University.
        description: | # this will include new lines to allow paragraphs
          We compete in the AICity Challenge Anomaly Detection Track and in this paper, we proposed a dual-modality modularized methodology for the robust detection of abnormal vehicles. We introduced an integrated anomaly detection pipeline comprising multi-level feature extraction and fusion. It's worth noticing that we explore the boundary of detecting crashing vehicles. The experiment conducted on the challenge dataset shows a extraordinary results, ranking 3rd place among all competitors and slightly lower than the winner and runner-up.
      
      - layout: top-middle
        title: on working!

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shanghai AI Lab Intern
        link: https://www.shlab.org.cn/
        # link_text: Pujiang Lab
        sub_title: Research Apprentice
        caption: October 2021 - Present
        quote: >
          Make a full use of the undergraduate time.
        description: | # this will include new lines to allow paragraphs
          It's a milestone that I started a full-time research life here. I joined the Autonomous Driving group in the Shanghai AI Lab and focused on 3D Object Detection. LiDAR and multi-view camera data that came from open-source datasets were processed and utilized to chase novel detection methods in various scenes.


  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer science, here are some of my other interests and hobbies.(not listed in order, lol):
      - Fitness
      - Writing
      - Photography and Travelling
      - Sleep

      -layout: bottom-mid
       Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
